name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install flake8 and run
        run: python3 -m pip install flake8 && python3 -m flake8 app
    
    
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker images and run tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test
    
    needs: [lint]
